print("me fale um pouco sobre voce")
nome = input("qual seu nome?")
idade = int(input("qual sua idade?"))
curso = input("qual seu curso?")
hb = input("qual seu hobbie?")
print()
print("obrigado por me conta um pouco sobre voce!\n")
print("aprenso a voce as informaçoes que voce compartilhou\n")
print("seu nome é:", nome, "\nsua idade é:", idade, "\nseu curso é:", curso,"\nseu hobbie é:", hb)
