CREATE DATABASE CASTELLOVERS;
USE CASTELLOVERS;

CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_ALUNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (60) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    STATUS_ALUNO ENUM ('ATIVO','INATIVO','CONCLUIDO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--Visualizar todos os BD

SHOW SCHEMAS;

--Visualizar tabelas do db

SHOW TABLES;

--Descrição de atributos da tabela Aluno

DESCRIBE ALUNOS;

-- Apagar bd

DROP DATABASE CASTELLOVERS;